image: docker:latest

services:
  -
    name: docker:dind
    command:
        - "--insecure-registry=registry.docker.tianhai.info:5000"
        - "--registry-mirror=https://docker.mirrors.ustc.edu.cn/"

before_script:
  - export TIANHAI_REGISTRY="registry.docker.tianhai.info:5000"
  - export THIS_IMAGE_NAME="oujiangapp/oa-fetcher"

build-master:
  stage: build
  script:
    - docker build --pull -t "$TIANHAI_REGISTRY/$THIS_IMAGE_NAME:dev-master" .
    - docker push "$TIANHAI_REGISTRY/$THIS_IMAGE_NAME:dev-master"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$TIANHAI_REGISTRY/$THIS_IMAGE_NAME:$CI_COMMIT_REF_SLUG" .
    - docker push "$TIANHAI_REGISTRY/$THIS_IMAGE_NAME:$CI_COMMIT_REF_SLUG"
  except:
    - master
